# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AcqParamsWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AcqParamsWidget(object):
    def setupUi(self, AcqParamsWidget):
        AcqParamsWidget.setObjectName("AcqParamsWidget")
        AcqParamsWidget.resize(160, 135)
        self.gridLayout = QtWidgets.QGridLayout(AcqParamsWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(AcqParamsWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.leAperBlock = QtWidgets.QLineEdit(AcqParamsWidget)
        self.leAperBlock.setObjectName("leAperBlock")
        self.gridLayout.addWidget(self.leAperBlock, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(AcqParamsWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.leSperA = QtWidgets.QLineEdit(AcqParamsWidget)
        self.leSperA.setObjectName("leSperA")
        self.gridLayout.addWidget(self.leSperA, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(AcqParamsWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.leNBlocks = QtWidgets.QLineEdit(AcqParamsWidget)
        self.leNBlocks.setObjectName("leNBlocks")
        self.gridLayout.addWidget(self.leNBlocks, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(AcqParamsWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.leTriggerDelay = QtWidgets.QLineEdit(AcqParamsWidget)
        self.leTriggerDelay.setObjectName("leTriggerDelay")
        self.gridLayout.addWidget(self.leTriggerDelay, 3, 1, 1, 1)

        self.retranslateUi(AcqParamsWidget)
        QtCore.QMetaObject.connectSlotsByName(AcqParamsWidget)

    def retranslateUi(self, AcqParamsWidget):
        _translate = QtCore.QCoreApplication.translate
        AcqParamsWidget.setWindowTitle(_translate("AcqParamsWidget", "GroupBox"))
        self.label.setText(_translate("AcqParamsWidget", "Ascan/block"))
        self.label_2.setText(_translate("AcqParamsWidget", "samp/Ascan"))
        self.label_3.setText(_translate("AcqParamsWidget", "# blocks"))
        self.label_4.setText(_translate("AcqParamsWidget", "trig dly(samples)"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AcqParamsWidget = QtWidgets.QGroupBox()
    ui = Ui_AcqParamsWidget()
    ui.setupUi(AcqParamsWidget)
    AcqParamsWidget.show()
    sys.exit(app.exec_())
