# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'AimingScanConfigWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AimingScanConfigWidget(object):
    def setupUi(self, AimingScanConfigWidget):
        AimingScanConfigWidget.setObjectName("AimingScanConfigWidget")
        AimingScanConfigWidget.resize(153, 135)
        self.gridLayout = QtWidgets.QGridLayout(AimingScanConfigWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(AimingScanConfigWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.leAextent = QtWidgets.QLineEdit(AimingScanConfigWidget)
        self.leAextent.setMinimumSize(QtCore.QSize(40, 0))
        self.leAextent.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leAextent.setObjectName("leAextent")
        self.gridLayout.addWidget(self.leAextent, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(AimingScanConfigWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 1)
        self.leAperB = QtWidgets.QLineEdit(AimingScanConfigWidget)
        self.leAperB.setMinimumSize(QtCore.QSize(40, 0))
        self.leAperB.setMaximumSize(QtCore.QSize(160, 16777215))
        self.leAperB.setObjectName("leAperB")
        self.gridLayout.addWidget(self.leAperB, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(AimingScanConfigWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 2)
        self.leBperV = QtWidgets.QLineEdit(AimingScanConfigWidget)
        self.leBperV.setMinimumSize(QtCore.QSize(40, 0))
        self.leBperV.setMaximumSize(QtCore.QSize(160, 16777215))
        self.leBperV.setObjectName("leBperV")
        self.gridLayout.addWidget(self.leBperV, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(AimingScanConfigWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 2)
        self.cbBidirectional = QtWidgets.QCheckBox(AimingScanConfigWidget)
        self.cbBidirectional.setText("")
        self.cbBidirectional.setObjectName("cbBidirectional")
        self.gridLayout.addWidget(self.cbBidirectional, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(AimingScanConfigWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.dsbAngle = QtWidgets.QDoubleSpinBox(AimingScanConfigWidget)
        self.dsbAngle.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dsbAngle.setObjectName("dsbAngle")
        self.gridLayout.addWidget(self.dsbAngle, 4, 1, 1, 1)

        self.retranslateUi(AimingScanConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(AimingScanConfigWidget)

    def retranslateUi(self, AimingScanConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        AimingScanConfigWidget.setWindowTitle(_translate("AimingScanConfigWidget", "Form"))
        self.label.setText(_translate("AimingScanConfigWidget", "Aim extent"))
        self.leAextent.setText(_translate("AimingScanConfigWidget", "-1,1"))
        self.label_3.setText(_translate("AimingScanConfigWidget", "A per B"))
        self.leAperB.setText(_translate("AimingScanConfigWidget", "500"))
        self.label_4.setText(_translate("AimingScanConfigWidget", "B per V"))
        self.leBperV.setText(_translate("AimingScanConfigWidget", "50"))
        self.label_2.setText(_translate("AimingScanConfigWidget", "bidirectional?"))
        self.label_6.setText(_translate("AimingScanConfigWidget", "Angle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AimingScanConfigWidget = QtWidgets.QWidget()
    ui = Ui_AimingScanConfigWidget()
    ui.setupUi(AimingScanConfigWidget)
    AimingScanConfigWidget.show()
    sys.exit(app.exec_())
