# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CbFileSaveWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_CbFileSaveWidget(object):
    def setupUi(self, CbFileSaveWidget):
        CbFileSaveWidget.setObjectName("CbFileSaveWidget")
        CbFileSaveWidget.resize(468, 41)
        self.horizontalLayout = QtWidgets.QHBoxLayout(CbFileSaveWidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self._cb = QtWidgets.QCheckBox(CbFileSaveWidget)
        self._cb.setObjectName("_cb")
        self.horizontalLayout.addWidget(self._cb)
        self._pb = QtWidgets.QPushButton(CbFileSaveWidget)
        self._pb.setObjectName("_pb")
        self.horizontalLayout.addWidget(self._pb)
        self._label = QtWidgets.QLabel(CbFileSaveWidget)
        self._label.setObjectName("_label")
        self.horizontalLayout.addWidget(self._label)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 4)

        self.retranslateUi(CbFileSaveWidget)
        QtCore.QMetaObject.connectSlotsByName(CbFileSaveWidget)

    def retranslateUi(self, CbFileSaveWidget):
        _translate = QtCore.QCoreApplication.translate
        CbFileSaveWidget.setWindowTitle(_translate("CbFileSaveWidget", "Form"))
        self._cb.setText(_translate("CbFileSaveWidget", "Save ascans"))
        self._pb.setText(_translate("CbFileSaveWidget", "Select File"))
        self._label.setText(_translate("CbFileSaveWidget", "C:datafolderfilename-ascans.npy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    CbFileSaveWidget = QtWidgets.QWidget()
    ui = Ui_CbFileSaveWidget()
    ui.setupUi(CbFileSaveWidget)
    CbFileSaveWidget.show()
    sys.exit(app.exec_())
