# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'DispersionWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DispersionWidget(object):
    def setupUi(self, DispersionWidget):
        DispersionWidget.setObjectName("DispersionWidget")
        DispersionWidget.resize(279, 76)
        self.verticalLayout = QtWidgets.QVBoxLayout(DispersionWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_26 = QtWidgets.QLabel(DispersionWidget)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout.addWidget(self.label_26)
        self.dsbDispersion0 = ScienDSpinBox(DispersionWidget)
        self.dsbDispersion0.setObjectName("dsbDispersion0")
        self.horizontalLayout.addWidget(self.dsbDispersion0)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_27 = QtWidgets.QLabel(DispersionWidget)
        self.label_27.setObjectName("label_27")
        self.horizontalLayout_2.addWidget(self.label_27)
        self.dsbDispersion1 = ScienDSpinBox(DispersionWidget)
        self.dsbDispersion1.setObjectName("dsbDispersion1")
        self.horizontalLayout_2.addWidget(self.dsbDispersion1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(DispersionWidget)
        QtCore.QMetaObject.connectSlotsByName(DispersionWidget)

    def retranslateUi(self, DispersionWidget):
        _translate = QtCore.QCoreApplication.translate
        DispersionWidget.setWindowTitle(_translate("DispersionWidget", "Form"))
        self.label_26.setText(_translate("DispersionWidget", "dispersion[0] (s/Hz/m)"))
        self.label_27.setText(_translate("DispersionWidget", "dispersion[1] (s/Hz**2/m)"))
from scientific_spinbox_2 import ScienDSpinBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DispersionWidget = QtWidgets.QWidget()
    ui = Ui_DispersionWidget()
    ui.setupUi(DispersionWidget)
    DispersionWidget.show()
    sys.exit(app.exec_())
