# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GalvoTuningScanConfigWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GalvoTuningScanConfigWidget(object):
    def setupUi(self, GalvoTuningScanConfigWidget):
        GalvoTuningScanConfigWidget.setObjectName("GalvoTuningScanConfigWidget")
        GalvoTuningScanConfigWidget.resize(233, 189)
        self.gridLayout = QtWidgets.QGridLayout(GalvoTuningScanConfigWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(GalvoTuningScanConfigWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.leAperB = QtWidgets.QLineEdit(GalvoTuningScanConfigWidget)
        self.leAperB.setMinimumSize(QtCore.QSize(40, 0))
        self.leAperB.setMaximumSize(QtCore.QSize(160, 16777215))
        self.leAperB.setObjectName("leAperB")
        self.gridLayout.addWidget(self.leAperB, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(GalvoTuningScanConfigWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 2)
        self.leTextent = QtWidgets.QLineEdit(GalvoTuningScanConfigWidget)
        self.leTextent.setMinimumSize(QtCore.QSize(40, 0))
        self.leTextent.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leTextent.setObjectName("leTextent")
        self.gridLayout.addWidget(self.leTextent, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(GalvoTuningScanConfigWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.leLperV = QtWidgets.QLineEdit(GalvoTuningScanConfigWidget)
        self.leLperV.setMinimumSize(QtCore.QSize(40, 0))
        self.leLperV.setMaximumSize(QtCore.QSize(160, 16777215))
        self.leLperV.setObjectName("leLperV")
        self.gridLayout.addWidget(self.leLperV, 2, 2, 1, 1)

        self.retranslateUi(GalvoTuningScanConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(GalvoTuningScanConfigWidget)

    def retranslateUi(self, GalvoTuningScanConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        GalvoTuningScanConfigWidget.setWindowTitle(_translate("GalvoTuningScanConfigWidget", "Form"))
        self.label_3.setText(_translate("GalvoTuningScanConfigWidget", "A per B"))
        self.leAperB.setText(_translate("GalvoTuningScanConfigWidget", "500"))
        self.label_4.setText(_translate("GalvoTuningScanConfigWidget", "Lines per V"))
        self.leTextent.setText(_translate("GalvoTuningScanConfigWidget", "-1,1"))
        self.label.setText(_translate("GalvoTuningScanConfigWidget", "Line extent"))
        self.leLperV.setText(_translate("GalvoTuningScanConfigWidget", "500"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GalvoTuningScanConfigWidget = QtWidgets.QWidget()
    ui = Ui_GalvoTuningScanConfigWidget()
    ui.setupUi(GalvoTuningScanConfigWidget)
    GalvoTuningScanConfigWidget.show()
    sys.exit(app.exec_())
