# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LineScanConfigWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LineScanConfigWidget(object):
    def setupUi(self, LineScanConfigWidget):
        LineScanConfigWidget.setObjectName("LineScanConfigWidget")
        LineScanConfigWidget.resize(179, 183)
        self.gridLayout = QtWidgets.QGridLayout(LineScanConfigWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(LineScanConfigWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.leXextent = QtWidgets.QLineEdit(LineScanConfigWidget)
        self.leXextent.setMinimumSize(QtCore.QSize(40, 0))
        self.leXextent.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leXextent.setObjectName("leXextent")
        self.gridLayout.addWidget(self.leXextent, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(LineScanConfigWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 1, 0, 1, 2)
        self.leAperB = QtWidgets.QLineEdit(LineScanConfigWidget)
        self.leAperB.setMinimumSize(QtCore.QSize(40, 0))
        self.leAperB.setMaximumSize(QtCore.QSize(160, 16777215))
        self.leAperB.setObjectName("leAperB")
        self.gridLayout.addWidget(self.leAperB, 1, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(LineScanConfigWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 2)
        self.leLperV = QtWidgets.QLineEdit(LineScanConfigWidget)
        self.leLperV.setMinimumSize(QtCore.QSize(40, 0))
        self.leLperV.setMaximumSize(QtCore.QSize(160, 16777215))
        self.leLperV.setObjectName("leLperV")
        self.gridLayout.addWidget(self.leLperV, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(LineScanConfigWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 2)
        self.cbBidirectional = QtWidgets.QCheckBox(LineScanConfigWidget)
        self.cbBidirectional.setText("")
        self.cbBidirectional.setObjectName("cbBidirectional")
        self.gridLayout.addWidget(self.cbBidirectional, 3, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(LineScanConfigWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 4, 0, 1, 1)
        self.dsbAngle = QtWidgets.QDoubleSpinBox(LineScanConfigWidget)
        self.dsbAngle.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dsbAngle.setObjectName("dsbAngle")
        self.gridLayout.addWidget(self.dsbAngle, 4, 1, 1, 2)

        self.retranslateUi(LineScanConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(LineScanConfigWidget)

    def retranslateUi(self, LineScanConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        LineScanConfigWidget.setWindowTitle(_translate("LineScanConfigWidget", "Form"))
        self.label.setText(_translate("LineScanConfigWidget", "Line extent"))
        self.leXextent.setText(_translate("LineScanConfigWidget", "-1,1"))
        self.label_3.setText(_translate("LineScanConfigWidget", "A per B"))
        self.leAperB.setText(_translate("LineScanConfigWidget", "500"))
        self.label_4.setText(_translate("LineScanConfigWidget", "Lines per V"))
        self.leLperV.setText(_translate("LineScanConfigWidget", "500"))
        self.label_2.setText(_translate("LineScanConfigWidget", "bidirectional?"))
        self.label_6.setText(_translate("LineScanConfigWidget", "Angle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LineScanConfigWidget = QtWidgets.QWidget()
    ui = Ui_LineScanConfigWidget()
    ui.setupUi(LineScanConfigWidget)
    LineScanConfigWidget.show()
    sys.exit(app.exec_())
