# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LineScanConfigWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LineScanConfigWidget(object):
    def setupUi(self, LineScanConfigWidget):
        LineScanConfigWidget.setObjectName("LineScanConfigWidget")
        LineScanConfigWidget.resize(206, 273)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(LineScanConfigWidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.label = QtWidgets.QLabel(LineScanConfigWidget)
        self.label.setObjectName("label")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.leLINEextent = QtWidgets.QLineEdit(LineScanConfigWidget)
        self.leLINEextent.setMinimumSize(QtCore.QSize(40, 0))
        self.leLINEextent.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leLINEextent.setObjectName("leLINEextent")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leLINEextent)
        self.label_3 = QtWidgets.QLabel(LineScanConfigWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.leAperB = QtWidgets.QLineEdit(LineScanConfigWidget)
        self.leAperB.setMinimumSize(QtCore.QSize(40, 0))
        self.leAperB.setMaximumSize(QtCore.QSize(40, 16777215))
        self.leAperB.setObjectName("leAperB")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leAperB)
        self.label_4 = QtWidgets.QLabel(LineScanConfigWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.leLperV = QtWidgets.QLineEdit(LineScanConfigWidget)
        self.leLperV.setMinimumSize(QtCore.QSize(40, 0))
        self.leLperV.setMaximumSize(QtCore.QSize(40, 16777215))
        self.leLperV.setObjectName("leLperV")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.leLperV)
        self.label_6 = QtWidgets.QLabel(LineScanConfigWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.dsbAngle = QtWidgets.QDoubleSpinBox(LineScanConfigWidget)
        self.dsbAngle.setMaximumSize(QtCore.QSize(40, 16777215))
        self.dsbAngle.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dsbAngle.setObjectName("dsbAngle")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.dsbAngle)
        self.verticalLayout_2.addLayout(self.formLayout_2)
        self.cbBidirectional = QtWidgets.QCheckBox(LineScanConfigWidget)
        self.cbBidirectional.setMaximumSize(QtCore.QSize(120, 16777215))
        self.cbBidirectional.setObjectName("cbBidirectional")
        self.verticalLayout_2.addWidget(self.cbBidirectional)
        self.gbStrobeOutput = QtWidgets.QGroupBox(LineScanConfigWidget)
        self.gbStrobeOutput.setCheckable(True)
        self.gbStrobeOutput.setObjectName("gbStrobeOutput")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.gbStrobeOutput)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.label_5 = QtWidgets.QLabel(self.gbStrobeOutput)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.leBscanTriggerIndex = QtWidgets.QLineEdit(self.gbStrobeOutput)
        self.leBscanTriggerIndex.setMaximumSize(QtCore.QSize(40, 16777215))
        self.leBscanTriggerIndex.setObjectName("leBscanTriggerIndex")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.leBscanTriggerIndex)
        self.label_7 = QtWidgets.QLabel(self.gbStrobeOutput)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.leOutputLine = QtWidgets.QLineEdit(self.gbStrobeOutput)
        self.leOutputLine.setMaximumSize(QtCore.QSize(40, 16777215))
        self.leOutputLine.setObjectName("leOutputLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.leOutputLine)
        self.verticalLayout.addLayout(self.formLayout)
        self.pbTriggerAndSave = QtWidgets.QPushButton(self.gbStrobeOutput)
        self.pbTriggerAndSave.setObjectName("pbTriggerAndSave")
        self.verticalLayout.addWidget(self.pbTriggerAndSave)
        self.verticalLayout_2.addWidget(self.gbStrobeOutput)

        self.retranslateUi(LineScanConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(LineScanConfigWidget)

    def retranslateUi(self, LineScanConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        LineScanConfigWidget.setWindowTitle(_translate("LineScanConfigWidget", "Form"))
        self.label.setText(_translate("LineScanConfigWidget", "Line extent"))
        self.leLINEextent.setText(_translate("LineScanConfigWidget", "-1,1"))
        self.label_3.setText(_translate("LineScanConfigWidget", "A per B"))
        self.leAperB.setText(_translate("LineScanConfigWidget", "500"))
        self.label_4.setText(_translate("LineScanConfigWidget", "Lines per V"))
        self.leLperV.setText(_translate("LineScanConfigWidget", "500"))
        self.label_6.setText(_translate("LineScanConfigWidget", "Angle"))
        self.cbBidirectional.setText(_translate("LineScanConfigWidget", "Bidirectional"))
        self.gbStrobeOutput.setTitle(_translate("LineScanConfigWidget", "Enable scan with output trigger"))
        self.label_5.setText(_translate("LineScanConfigWidget", "Trigger at bscan #"))
        self.leBscanTriggerIndex.setText(_translate("LineScanConfigWidget", "0"))
        self.label_7.setText(_translate("LineScanConfigWidget", "device line#"))
        self.pbTriggerAndSave.setText(_translate("LineScanConfigWidget", "Trigger+Save"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    LineScanConfigWidget = QtWidgets.QWidget()
    ui = Ui_LineScanConfigWidget()
    ui.setupUi(LineScanConfigWidget)
    LineScanConfigWidget.show()
    sys.exit(app.exec_())
