# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OCTDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OCTDialog(object):
    def setupUi(self, OCTDialog):
        OCTDialog.setObjectName("OCTDialog")
        OCTDialog.resize(1089, 851)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(OCTDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayoutSidebar = QtWidgets.QVBoxLayout()
        self.verticalLayoutSidebar.setObjectName("verticalLayoutSidebar")
        self.widgetScanConfig = ScanConfigWidget(OCTDialog)
        self.widgetScanConfig.setMinimumSize(QtCore.QSize(0, 80))
        self.widgetScanConfig.setObjectName("widgetScanConfig")
        self.verticalLayoutSidebar.addWidget(self.widgetScanConfig)
        self.widgetAcqParams = AcqParamsWidget(OCTDialog)
        self.widgetAcqParams.setMinimumSize(QtCore.QSize(0, 80))
        self.widgetAcqParams.setObjectName("widgetAcqParams")
        self.verticalLayoutSidebar.addWidget(self.widgetAcqParams)
        self.pbEtc = QtWidgets.QPushButton(OCTDialog)
        self.pbEtc.setObjectName("pbEtc")
        self.verticalLayoutSidebar.addWidget(self.pbEtc)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayoutSidebar.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayoutSidebar)
        self.widgetDummy = QtWidgets.QWidget(OCTDialog)
        self.widgetDummy.setMinimumSize(QtCore.QSize(800, 800))
        self.widgetDummy.setObjectName("widgetDummy")
        self.horizontalLayout_2.addWidget(self.widgetDummy)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbStart = QtWidgets.QPushButton(OCTDialog)
        self.pbStart.setObjectName("pbStart")
        self.horizontalLayout.addWidget(self.pbStart)
        self.pbStop = QtWidgets.QPushButton(OCTDialog)
        self.pbStop.setObjectName("pbStop")
        self.horizontalLayout.addWidget(self.pbStop)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_2 = CbAscansFileSaveWidget(OCTDialog)
        self.widget_2.setMinimumSize(QtCore.QSize(800, 0))
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout.addWidget(self.widget_2)
        self.widget = CbSpectraFileSaveWidget(OCTDialog)
        self.widget.setMinimumSize(QtCore.QSize(800, 0))
        self.widget.setObjectName("widget")
        self.verticalLayout.addWidget(self.widget)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(OCTDialog)
        QtCore.QMetaObject.connectSlotsByName(OCTDialog)

    def retranslateUi(self, OCTDialog):
        _translate = QtCore.QCoreApplication.translate
        OCTDialog.setWindowTitle(_translate("OCTDialog", "UCD OCT Dev Tool"))
        self.pbEtc.setText(_translate("OCTDialog", "Etc"))
        self.pbStart.setText(_translate("OCTDialog", "Start"))
        self.pbStop.setText(_translate("OCTDialog", "Stop"))
from AcqParamsWidget import AcqParamsWidget
from CbFileSaveWidget import CbAscansFileSaveWidget, CbSpectraFileSaveWidget
from ScanConfigWidget import ScanConfigWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OCTDialog = QtWidgets.QDialog()
    ui = Ui_OCTDialog()
    ui.setupUi(OCTDialog)
    OCTDialog.show()
    sys.exit(app.exec_())
