# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OCTDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OCTDialog(object):
    def setupUi(self, OCTDialog):
        OCTDialog.setObjectName("OCTDialog")
        OCTDialog.resize(1089, 753)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(OCTDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.pbStart = QtWidgets.QPushButton(OCTDialog)
        self.pbStart.setObjectName("pbStart")
        self.verticalLayout.addWidget(self.pbStart)
        self.pbStop = QtWidgets.QPushButton(OCTDialog)
        self.pbStop.setObjectName("pbStop")
        self.verticalLayout.addWidget(self.pbStop)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.tabWidgetPlots = QtWidgets.QTabWidget(OCTDialog)
        self.tabWidgetPlots.setObjectName("tabWidgetPlots")
        self.horizontalLayout_2.addWidget(self.tabWidgetPlots)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.labelStatus = QtWidgets.QLabel(OCTDialog)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout_2.addWidget(self.labelStatus)

        self.retranslateUi(OCTDialog)
        self.tabWidgetPlots.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(OCTDialog)

    def retranslateUi(self, OCTDialog):
        _translate = QtCore.QCoreApplication.translate
        OCTDialog.setWindowTitle(_translate("OCTDialog", "UCD OCT Dev Tool"))
        self.pbStart.setText(_translate("OCTDialog", "Start"))
        self.pbStop.setText(_translate("OCTDialog", "Stop"))
        self.labelStatus.setText(_translate("OCTDialog", "TextLabel"))
