# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OCTUiMainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OCTUiMainWindow(object):
    def setupUi(self, OCTUiMainWindow):
        OCTUiMainWindow.setObjectName("OCTUiMainWindow")
        OCTUiMainWindow.resize(996, 944)
        self.centralwidget = QtWidgets.QWidget(OCTUiMainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.widgetScanConfig = ScanConfigWidget(self.centralwidget)
        self.widgetScanConfig.setMinimumSize(QtCore.QSize(0, 80))
        self.widgetScanConfig.setObjectName("widgetScanConfig")
        self.verticalLayout_3.addWidget(self.widgetScanConfig)
        self.pbEtc = QtWidgets.QPushButton(self.centralwidget)
        self.pbEtc.setObjectName("pbEtc")
        self.verticalLayout_3.addWidget(self.pbEtc)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pbStart = QtWidgets.QPushButton(self.centralwidget)
        self.pbStart.setObjectName("pbStart")
        self.horizontalLayout_4.addWidget(self.pbStart)
        self.pbStop = QtWidgets.QPushButton(self.centralwidget)
        self.pbStop.setObjectName("pbStop")
        self.horizontalLayout_4.addWidget(self.pbStop)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.stackedWidgetDummy = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidgetDummy.setMinimumSize(QtCore.QSize(800, 800))
        self.stackedWidgetDummy.setObjectName("stackedWidgetDummy")
        self.stackedWidgetDummyPage1 = QtWidgets.QWidget()
        self.stackedWidgetDummyPage1.setObjectName("stackedWidgetDummyPage1")
        self.stackedWidgetDummy.addWidget(self.stackedWidgetDummyPage1)
        self.horizontalLayout_3.addWidget(self.stackedWidgetDummy)
        self.horizontalLayout_3.setStretch(1, 1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.gbSaveVolumes = SaveVolumeGroupBox(self.centralwidget)
        self.gbSaveVolumes.setObjectName("gbSaveVolumes")
        self.verticalLayout_4.addWidget(self.gbSaveVolumes)
        self.verticalLayout_5.addLayout(self.verticalLayout_4)
        OCTUiMainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(OCTUiMainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 996, 24))
        self.menubar.setObjectName("menubar")
        OCTUiMainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(OCTUiMainWindow)
        self.statusbar.setObjectName("statusbar")
        OCTUiMainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(OCTUiMainWindow)
        QtCore.QMetaObject.connectSlotsByName(OCTUiMainWindow)

    def retranslateUi(self, OCTUiMainWindow):
        _translate = QtCore.QCoreApplication.translate
        OCTUiMainWindow.setWindowTitle(_translate("OCTUiMainWindow", "MainWindow"))
        self.pbEtc.setText(_translate("OCTUiMainWindow", "Engine Configuration"))
        self.pbStart.setText(_translate("OCTUiMainWindow", "Start"))
        self.pbStop.setText(_translate("OCTUiMainWindow", "Stop"))
        self.gbSaveVolumes.setTitle(_translate("OCTUiMainWindow", "Saving Volume Data"))
from SaveVolumeGroupBox import SaveVolumeGroupBox
from ScanConfigWidget import ScanConfigWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OCTUiMainWindow = QtWidgets.QMainWindow()
    ui = Ui_OCTUiMainWindow()
    ui.setupUi(OCTUiMainWindow)
    OCTUiMainWindow.show()
    sys.exit(app.exec_())
