# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'OCTDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_OCTDialog(object):
    def setupUi(self, OCTDialog):
        OCTDialog.setObjectName("OCTDialog")
        OCTDialog.resize(986, 958)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(OCTDialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.widgetScanConfig = ScanConfigWidget(OCTDialog)
        self.widgetScanConfig.setMinimumSize(QtCore.QSize(0, 80))
        self.widgetScanConfig.setObjectName("widgetScanConfig")
        self.verticalLayout_2.addWidget(self.widgetScanConfig)
        self.widgetAcqParams = AcqParamsWidget(OCTDialog)
        self.widgetAcqParams.setMinimumSize(QtCore.QSize(0, 80))
        self.widgetAcqParams.setObjectName("widgetAcqParams")
        self.verticalLayout_2.addWidget(self.widgetAcqParams)
        self.widgetDispersion = DispersionWidget(OCTDialog)
        self.widgetDispersion.setObjectName("widgetDispersion")
        self.verticalLayout_2.addWidget(self.widgetDispersion)
        self.pbEtc = QtWidgets.QPushButton(OCTDialog)
        self.pbEtc.setObjectName("pbEtc")
        self.verticalLayout_2.addWidget(self.pbEtc)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbStart = QtWidgets.QPushButton(OCTDialog)
        self.pbStart.setObjectName("pbStart")
        self.horizontalLayout.addWidget(self.pbStart)
        self.pbStop = QtWidgets.QPushButton(OCTDialog)
        self.pbStop.setObjectName("pbStop")
        self.horizontalLayout.addWidget(self.pbStop)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_2.addLayout(self.verticalLayout_2)
        self.widgetDummy = QtWidgets.QWidget(OCTDialog)
        self.widgetDummy.setMinimumSize(QtCore.QSize(800, 800))
        self.widgetDummy.setObjectName("widgetDummy")
        self.horizontalLayout_2.addWidget(self.widgetDummy)
        self.horizontalLayout_2.setStretch(1, 1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gbSaveVolumes = SaveVolumeGroupBox(OCTDialog)
        self.gbSaveVolumes.setObjectName("gbSaveVolumes")
        self.verticalLayout.addWidget(self.gbSaveVolumes)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(OCTDialog)
        QtCore.QMetaObject.connectSlotsByName(OCTDialog)

    def retranslateUi(self, OCTDialog):
        _translate = QtCore.QCoreApplication.translate
        OCTDialog.setWindowTitle(_translate("OCTDialog", "UCD OCT Dev Tool"))
        self.pbEtc.setText(_translate("OCTDialog", "Etc"))
        self.pbStart.setText(_translate("OCTDialog", "Start"))
        self.pbStop.setText(_translate("OCTDialog", "Stop"))
        self.gbSaveVolumes.setTitle(_translate("OCTDialog", "Saving Volume Data"))
from AcqParamsWidget import AcqParamsWidget
from DispersionWidget import DispersionWidget
from SaveVolumeGroupBox import SaveVolumeGroupBox
from ScanConfigWidget import ScanConfigWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OCTDialog = QtWidgets.QDialog()
    ui = Ui_OCTDialog()
    ui.setupUi(OCTDialog)
    OCTDialog.show()
    sys.exit(app.exec_())
