# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RasterScanConfigWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RasterScanConfigWidget(object):
    def setupUi(self, RasterScanConfigWidget):
        RasterScanConfigWidget.setObjectName("RasterScanConfigWidget")
        RasterScanConfigWidget.resize(174, 185)
        self.gridLayout = QtWidgets.QGridLayout(RasterScanConfigWidget)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(RasterScanConfigWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 2)
        self.leFASTextent = QtWidgets.QLineEdit(RasterScanConfigWidget)
        self.leFASTextent.setMinimumSize(QtCore.QSize(40, 0))
        self.leFASTextent.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leFASTextent.setObjectName("leFASTextent")
        self.gridLayout.addWidget(self.leFASTextent, 0, 2, 1, 1)
        self.label_5 = QtWidgets.QLabel(RasterScanConfigWidget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 1, 0, 1, 2)
        self.leSLOWextent = QtWidgets.QLineEdit(RasterScanConfigWidget)
        self.leSLOWextent.setMinimumSize(QtCore.QSize(40, 0))
        self.leSLOWextent.setMaximumSize(QtCore.QSize(80, 16777215))
        self.leSLOWextent.setObjectName("leSLOWextent")
        self.gridLayout.addWidget(self.leSLOWextent, 1, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(RasterScanConfigWidget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 2)
        self.leAperB = QtWidgets.QLineEdit(RasterScanConfigWidget)
        self.leAperB.setMinimumSize(QtCore.QSize(40, 0))
        self.leAperB.setMaximumSize(QtCore.QSize(160, 16777215))
        self.leAperB.setObjectName("leAperB")
        self.gridLayout.addWidget(self.leAperB, 2, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(RasterScanConfigWidget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 2)
        self.leBperV = QtWidgets.QLineEdit(RasterScanConfigWidget)
        self.leBperV.setMinimumSize(QtCore.QSize(40, 0))
        self.leBperV.setMaximumSize(QtCore.QSize(160, 16777215))
        self.leBperV.setObjectName("leBperV")
        self.gridLayout.addWidget(self.leBperV, 3, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(RasterScanConfigWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 4, 0, 1, 2)
        self.cbBidirectional = QtWidgets.QCheckBox(RasterScanConfigWidget)
        self.cbBidirectional.setText("")
        self.cbBidirectional.setObjectName("cbBidirectional")
        self.gridLayout.addWidget(self.cbBidirectional, 4, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(RasterScanConfigWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 5, 0, 1, 1)
        self.dsbAngle = QtWidgets.QDoubleSpinBox(RasterScanConfigWidget)
        self.dsbAngle.setButtonSymbols(QtWidgets.QAbstractSpinBox.NoButtons)
        self.dsbAngle.setObjectName("dsbAngle")
        self.gridLayout.addWidget(self.dsbAngle, 5, 1, 1, 2)

        self.retranslateUi(RasterScanConfigWidget)
        QtCore.QMetaObject.connectSlotsByName(RasterScanConfigWidget)

    def retranslateUi(self, RasterScanConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        RasterScanConfigWidget.setWindowTitle(_translate("RasterScanConfigWidget", "Form"))
        self.label.setText(_translate("RasterScanConfigWidget", "fast extent"))
        self.leFASTextent.setText(_translate("RasterScanConfigWidget", "-1,1"))
        self.label_5.setText(_translate("RasterScanConfigWidget", "slow extent"))
        self.leSLOWextent.setText(_translate("RasterScanConfigWidget", "-1,1"))
        self.label_3.setText(_translate("RasterScanConfigWidget", "A per B"))
        self.leAperB.setText(_translate("RasterScanConfigWidget", "500"))
        self.label_4.setText(_translate("RasterScanConfigWidget", "B per Vol"))
        self.leBperV.setText(_translate("RasterScanConfigWidget", "500"))
        self.label_2.setText(_translate("RasterScanConfigWidget", "bidirectional?"))
        self.label_6.setText(_translate("RasterScanConfigWidget", "Angle"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RasterScanConfigWidget = QtWidgets.QWidget()
    ui = Ui_RasterScanConfigWidget()
    ui.setupUi(RasterScanConfigWidget)
    RasterScanConfigWidget.show()
    sys.exit(app.exec_())
