# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScanBuilderDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScanBuilderDialog(object):
    def setupUi(self, ScanBuilderDialog):
        ScanBuilderDialog.setObjectName("ScanBuilderDialog")
        ScanBuilderDialog.resize(231, 242)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(ScanBuilderDialog)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.groupBox = QtWidgets.QGroupBox(ScanBuilderDialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 2, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.leLimitsBscanMin = QtWidgets.QLineEdit(self.groupBox)
        self.leLimitsBscanMin.setObjectName("leLimitsBscanMin")
        self.gridLayout.addWidget(self.leLimitsBscanMin, 1, 1, 1, 1)
        self.leLimitsBscanMax = QtWidgets.QLineEdit(self.groupBox)
        self.leLimitsBscanMax.setObjectName("leLimitsBscanMax")
        self.gridLayout.addWidget(self.leLimitsBscanMax, 1, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 0, 1, 1)
        self.leLimitsVolumeMin = QtWidgets.QLineEdit(self.groupBox)
        self.leLimitsVolumeMin.setObjectName("leLimitsVolumeMin")
        self.gridLayout.addWidget(self.leLimitsVolumeMin, 2, 1, 1, 1)
        self.leLimitsVolumeMax = QtWidgets.QLineEdit(self.groupBox)
        self.leLimitsVolumeMax.setObjectName("leLimitsVolumeMax")
        self.gridLayout.addWidget(self.leLimitsVolumeMax, 2, 2, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(ScanBuilderDialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.leLimitsOffsetX = QtWidgets.QLineEdit(ScanBuilderDialog)
        self.leLimitsOffsetX.setObjectName("leLimitsOffsetX")
        self.horizontalLayout.addWidget(self.leLimitsOffsetX)
        self.leLimitsOffsetY = QtWidgets.QLineEdit(ScanBuilderDialog)
        self.leLimitsOffsetY.setObjectName("leLimitsOffsetY")
        self.horizontalLayout.addWidget(self.leLimitsOffsetY)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pbUpdate = QtWidgets.QPushButton(ScanBuilderDialog)
        self.pbUpdate.setObjectName("pbUpdate")
        self.verticalLayout.addWidget(self.pbUpdate)
        self.pbExit = QtWidgets.QPushButton(ScanBuilderDialog)
        self.pbExit.setObjectName("pbExit")
        self.verticalLayout.addWidget(self.pbExit)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)

        self.retranslateUi(ScanBuilderDialog)
        QtCore.QMetaObject.connectSlotsByName(ScanBuilderDialog)

    def retranslateUi(self, ScanBuilderDialog):
        _translate = QtCore.QCoreApplication.translate
        ScanBuilderDialog.setWindowTitle(_translate("ScanBuilderDialog", "Dialog"))
        self.groupBox.setTitle(_translate("ScanBuilderDialog", "Scan Parameters"))
        self.label_4.setText(_translate("ScanBuilderDialog", "Min"))
        self.label_5.setText(_translate("ScanBuilderDialog", "Max"))
        self.label.setText(_translate("ScanBuilderDialog", "bscan"))
        self.leLimitsBscanMin.setText(_translate("ScanBuilderDialog", "-2"))
        self.leLimitsBscanMax.setText(_translate("ScanBuilderDialog", "2"))
        self.label_2.setText(_translate("ScanBuilderDialog", "volume"))
        self.leLimitsVolumeMin.setText(_translate("ScanBuilderDialog", "-2"))
        self.leLimitsVolumeMax.setText(_translate("ScanBuilderDialog", "2"))
        self.label_3.setText(_translate("ScanBuilderDialog", "offset"))
        self.leLimitsOffsetX.setText(_translate("ScanBuilderDialog", "0"))
        self.leLimitsOffsetY.setText(_translate("ScanBuilderDialog", "0"))
        self.pbUpdate.setText(_translate("ScanBuilderDialog", "Update"))
        self.pbExit.setText(_translate("ScanBuilderDialog", "Exit"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScanBuilderDialog = QtWidgets.QDialog()
    ui = Ui_ScanBuilderDialog()
    ui.setupUi(ScanBuilderDialog)
    ScanBuilderDialog.show()
    sys.exit(app.exec_())
