# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ScanConfigWidget.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ScanConfigWidget(object):
    def setupUi(self, ScanConfigWidget):
        ScanConfigWidget.setObjectName("ScanConfigWidget")
        ScanConfigWidget.resize(214, 277)
        self.verticalLayout = QtWidgets.QVBoxLayout(ScanConfigWidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_6 = QtWidgets.QLabel(ScanConfigWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.cbScanTypes = QtWidgets.QComboBox(ScanConfigWidget)
        self.cbScanTypes.setObjectName("cbScanTypes")
        self.horizontalLayout.addWidget(self.cbScanTypes)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stackScanTypes = QtWidgets.QStackedWidget(ScanConfigWidget)
        self.stackScanTypes.setObjectName("stackScanTypes")
        self.verticalLayout.addWidget(self.stackScanTypes)

        self.retranslateUi(ScanConfigWidget)
        self.cbScanTypes.setCurrentIndex(-1)
        self.stackScanTypes.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(ScanConfigWidget)

    def retranslateUi(self, ScanConfigWidget):
        _translate = QtCore.QCoreApplication.translate
        ScanConfigWidget.setWindowTitle(_translate("ScanConfigWidget", "GroupBox"))
        ScanConfigWidget.setTitle(_translate("ScanConfigWidget", "Scan Configuration"))
        self.label_6.setText(_translate("ScanConfigWidget", "Scan type:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ScanConfigWidget = QtWidgets.QGroupBox()
    ui = Ui_ScanConfigWidget()
    ui.setupUi(ScanConfigWidget)
    ScanConfigWidget.show()
    sys.exit(app.exec_())
