# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SaveVolumeGroupBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SaveVolumeGroupBox(object):
    def setupUi(self, SaveVolumeGroupBox):
        SaveVolumeGroupBox.setObjectName("SaveVolumeGroupBox")
        SaveVolumeGroupBox.resize(400, 159)
        self.verticalLayout = QtWidgets.QVBoxLayout(SaveVolumeGroupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(SaveVolumeGroupBox)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pbSelectFolder = QtWidgets.QPushButton(self.groupBox)
        self.pbSelectFolder.setObjectName("pbSelectFolder")
        self.horizontalLayout.addWidget(self.pbSelectFolder)
        self.labelFolder = QtWidgets.QLabel(self.groupBox)
        self.labelFolder.setObjectName("labelFolder")
        self.horizontalLayout.addWidget(self.labelFolder)
        self.horizontalLayout.setStretch(0, 1)
        self.horizontalLayout.setStretch(1, 4)
        self.verticalLayout.addWidget(self.groupBox)
        self.labelStatus = QtWidgets.QLabel(SaveVolumeGroupBox)
        self.labelStatus.setObjectName("labelStatus")
        self.verticalLayout.addWidget(self.labelStatus)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.groupBox_2 = QtWidgets.QGroupBox(SaveVolumeGroupBox)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sbN = QtWidgets.QSpinBox(self.groupBox_2)
        self.sbN.setMinimum(1)
        self.sbN.setMaximum(16)
        self.sbN.setObjectName("sbN")
        self.horizontalLayout_2.addWidget(self.sbN)
        self.pbSaveFixedN = QtWidgets.QPushButton(self.groupBox_2)
        self.pbSaveFixedN.setObjectName("pbSaveFixedN")
        self.horizontalLayout_2.addWidget(self.pbSaveFixedN)
        self.horizontalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(SaveVolumeGroupBox)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pbSaveContinuous = QtWidgets.QPushButton(self.groupBox_3)
        self.pbSaveContinuous.setObjectName("pbSaveContinuous")
        self.horizontalLayout_4.addWidget(self.pbSaveContinuous)
        self.horizontalLayout_3.addWidget(self.groupBox_3)
        self.verticalLayout.addLayout(self.horizontalLayout_3)

        self.retranslateUi(SaveVolumeGroupBox)
        QtCore.QMetaObject.connectSlotsByName(SaveVolumeGroupBox)

    def retranslateUi(self, SaveVolumeGroupBox):
        _translate = QtCore.QCoreApplication.translate
        SaveVolumeGroupBox.setWindowTitle(_translate("SaveVolumeGroupBox", "Saving Volumes"))
        self.groupBox.setTitle(_translate("SaveVolumeGroupBox", "Data folder"))
        self.pbSelectFolder.setText(_translate("SaveVolumeGroupBox", "Select Folder"))
        self.labelFolder.setText(_translate("SaveVolumeGroupBox", "TextLabel"))
        self.labelStatus.setText(_translate("SaveVolumeGroupBox", "TextLabel"))
        self.groupBox_2.setTitle(_translate("SaveVolumeGroupBox", "Save Fixed # of Volumes"))
        self.pbSaveFixedN.setText(_translate("SaveVolumeGroupBox", "Save Fixed N"))
        self.groupBox_3.setTitle(_translate("SaveVolumeGroupBox", "Save Volumes (user stop)"))
        self.pbSaveContinuous.setText(_translate("SaveVolumeGroupBox", "Save Continuous"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SaveVolumeGroupBox = QtWidgets.QGroupBox()
    ui = Ui_SaveVolumeGroupBox()
    ui.setupUi(SaveVolumeGroupBox)
    SaveVolumeGroupBox.show()
    sys.exit(app.exec_())
